---
title: "Social Data Science" 
subtitle: "Project Workshop"
author: Dr. Thomas Davidson
institute: Rutgers University
date: December 6, 2021
output:
    beamer_presentation:
      theme: "Szeged"
      colortheme: "beaver"
      fonttheme: "structurebold"
      toc: false
      incremental: false
urlcolor: "blue"
header-includes:
  - \usepackage{multicol}
  - \usepackage{caption}
  - \usepackage{hyperref}
  - \captionsetup[figure]{font=scriptsize}
  - \captionsetup[figure]{labelformat=empty}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(dev = 'pdf')
library("knitr")
library("formatR")

opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
opts_chunk$set(tidy = FALSE)

knitr::knit_hooks$set(mysize = function(before, options, envir) {
  if (before) 
    return(options$size)
})
```

# Plan
1. Course updates
2. Presentations
3. Final project submissions
4. Recap of RShiny

# Course updates
- Homework amnesty
    - Missed homework assignments can be submitted until 12/8 (Wednesday) at 5pm
    - Submissions received after this deadline will receive a zero

# Presentations
- Project presentations in class on Wednesday
    - Add slides to shared deck (Canvas Announcement)
    - Prepare to talk for 5-10 minutes
    - Q&A from the audience

# Final Project Submission
- Due 12/16 at 5pm via Canvas
- Link to Github repository
    - Code used in project
    - README file containing a brief description of the project
        - Purpose
        - Data
        - Analysis and visualization
        - Conclusions
    - Link to live app on shinyapps.io
        
# Developing Shiny applications in R
## Information on example files
- `app.R` is an example of simple Shiny app to interactively plot correlations, along with other descriptive statistics
- `app2.R` modifies the previous app to use the `shinydashboards` framework
- `/app` is a directory containing two files, `ui.R` and `server.R` (the components of `app.R`)
  - `test.R` uses the files in `/app` to launch a local version of the app
  - `app_deploy_template.R` can be run to deploy the app to shinyapps.io.
    - You must add credentials and other information to this template before running it.

# Developing Shiny applications in R
## Deployment
- Apps can be deployed for free using the \href{https://www.shinyapps.io/}{Shiny Apps website}.* You just need to do the following:
  - Sign up (you can use Github account)
  - Get credentials (key and secret)
  - Authorize credentials
  - Package app in appropriate format
  - Deploy

* Free accounts are limited to 5 apps and 25 active hours a month. You will need to ensure you do not exceed these limits.

# Developing Shiny applications in R
## Extensions
- There are many extensions of the Shiny framework
  - \href{https://d3js.org/}{D3} for data-driven visualization. See \href{https://rstudio.github.io/r2d3/articles/shiny.html}{`r2d3` website}
  - \href{https://rstudio.github.io/leaflet/shiny.html}{Leaflet for interactive mapping}
  - \href{https://plotly-r.com/}{Plotly for interactive plots}
  - \href{https://github.com/cschwem2er/stminsights}{STMinsights} for exploring structural topic models (Week 9)
- \href{https://github.com/nanxstats/awesome-shiny-extensions}{This Github page} lists a ton of Shiny resources.

# Developing Shiny applications in R
## Further readings
- RStudio's \href{https://raw.githubusercontent.com/rstudio/cheatsheets/master/shiny.pdf}{Shiny cheatsheet} is a really useful quick reference.
- *\href{https://mastering-shiny.org/index.html}{Mastering Shiny}* by Hadley Wickham is available for free online.
- RStudio has a two and a half hour long \href{https://shiny.rstudio.com/tutorial/}{video tutorial}, along with a set of short online tutorials
- Lots of videos on YouTube